app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path("", include("base.urls")),
    path("almacen/", include("almacen.urls")),
    path("cuenta/", include("cuenta.urls")),
    path("documento/", include("documento.urls")),
    path("persona/", include("persona.urls")),
    path("moneda/", include("moneda.urls")),
    path("reporte/", include("reporte.urls")),

    path("prestamo/", include("prestamo.urls")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# Vista para los errores.
handler403 = "base.views.error403"

documento/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path("documento/list/", DocumentoListView.as_view(), name="documento-documento-list"),
    path("documento/list/<int:pk>/", DocumentoDetailView.as_view(), name="documento-documento-detail"),
    path("documento/list/<int:pk>/print/", DocumentoPrintDetailView.as_view(), name="documento-documento-print"),
    path("documento/create/", DocumentoCreateView.as_view(), name="documento-documento-create"),
    path("documento/factura/create/", DocumentoFacturaCreateView.as_view(), name="documento-documento-factura-create"),
    path("documento/entrada/create/", DocumentoEntradaCreateView.as_view(), name="documento-documento-entrada-create"),
    path("documento/salida/create/", DocumentoSalidaCreateView.as_view(), name="documento-documento-salida-create"),


    # Json views
    path("documento/json/calcular/monto-salida/", documentoCalcularMontoSalida, name="documento-documento-json-calcular-monto-salida"),
    path("documento/json/calcular/monto-entrada/", documentoCalcularMontoEntrada, name="documento-documento-json-calcular-monto-entrada"),


]

documento/models.py
from decimal import Decimal, DivisionUndefined
from django.db import models
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext as _
from simple_history.models import HistoricalRecords
#from auditoria.mixins import AuditMixin
from fuente import utils
from fuente.var import *




class DocumentoTipo(models.Model, utils.Texto):
    """
    Representa un tipo de documento.
    """
    codigo = models.CharField(_("Código"), max_length=10, unique=True)
    nombre = models.CharField(_("Nombre"), max_length=50, unique=True)
    modo = models.CharField(_("Modo"), max_length=20, choices=ENTRADA_SALIDA_CHOICES)
    tags = models.CharField(blank=True, max_length=512, editable=False)

    # Audiroría
    history = HistoricalRecords()

    class Meta:
        verbose_name = "Tipo de documento"
        verbose_name_plural = "Tipos de documentos"
    
    
    def __str__(self):
        return "{}: {}".format(self.codigo, self.nombre)

    def clean(self, *args, **kwargs):
        self.codigo = self.codigo.upper()
        self.nombre = self.nombre.upper()
        self.tags = self.GetEtiquetas((self.codigo, self.nombre))[:512]
        super().clean(*args, **kwargs)


class Documento(models.Model, utils.Texto):
    """
    Representa un documento (facturas, ordenes, entradas, etc.)
    """
    numero = models.IntegerField(_("Número"), editable=False, unique=True, default=-1)
    tipo = models.ForeignKey(DocumentoTipo, on_delete=models.CASCADE, help_text=_("Tipo de documento"))
    almacen = models.ForeignKey("almacen.Almacen", verbose_name=_("Almacén"), on_delete=models.PROTECT)
    persona = models.ForeignKey("persona.Persona", verbose_name=_("Persona"), on_delete=models.PROTECT, null=True, blank=True, default=None)
    fecha = models.DateField(_("Fecha"), default=timezone.now)
    fecha_creacion = models.DateTimeField(_("Fecha de creación"), auto_now_add=True)
    cajero = models.ForeignKey(User, verbose_name=_("Cajero"), editable=False, on_delete=models.SET_NULL, null=True, blank=True)
    # Movimientos
    entrada = models.ForeignKey("cuenta.Cuenta", related_name="entrada_set", verbose_name=_("Entrada"), null=True, blank=True, default=None, on_delete=models.CASCADE)
    salida = models.ForeignKey("cuenta.Cuenta", related_name="salida_set", verbose_name=_("Salida"), null=True, blank=True, default=None, on_delete=models.CASCADE)
    monto_entrada = models.DecimalField(_("Monto de entrada"), max_digits=17, decimal_places=2, validators=[MinValueValidator(0)], blank=True, help_text=_("Monto que trae el cliente"))
    monto_salida = models.DecimalField(_("Monto de salida"), max_digits=17, decimal_places=2, validators=[MinValueValidator(0)], blank=True, help_text=_("Monto que se le entregará al cliente"))
    tasa_entrada = models.DecimalField(_("Tasa de entrada"), max_digits=5, decimal_places=2, validators=[MinValueValidator(0)], default=None, null=True, blank=True, help_text=_("Tasa de entrada (compra)"))
    tasa_salida = models.DecimalField(_("Tasa de salida"), max_digits=5, decimal_places=2, validators=[MinValueValidator(0)], default=None, null=True, blank=True, help_text=_("Tasa de salida (venta)"))
    # La ganancia generada en esta transacción. La ganancia estará en la moneda de entrada.
    tasa_entrada_para_venta_del_dia = models.DecimalField("Tasa de venta del día", max_digits=5, decimal_places=2, default=0, blank=True)
    ganancia = models.DecimalField(_("Ganancia"), max_digits=17, decimal_places=2, default=0, blank=True)

    is_print = models.BooleanField(_("¿Se imprimió?"), default=False)

    nota = models.TextField(_("Nota"), blank=True)
    tags = models.TextField(blank=True, editable=False)

    # Audiroría
    history = HistoricalRecords()

    class Meta:
        verbose_name = _("Documento")
        verbose_name_plural = _("Documentos")
        ordering = ["-fecha", "-id"]

    def __str__(self):
        return "{}-{}".format(self.tipo.codigo, self.numero)

    def get_absolute_url(self):
        if (self.tipo.modo == FACTURA) and (self.is_print == False):
            self.is_print = True
            self.save()
            return reverse_lazy("documento-documento-print", kwargs={"pk": self.pk})
        return reverse_lazy("documento-documento-detail", kwargs={"pk": self.pk})

    def clean(self, *args, **kwargs):
        if (not self.monto_entrada):
            self.monto_entrada = 0
        if (not self.monto_salida):
            self.monto_salida = 0

        # El monto de entrada tiene que ser igual o mayor a 0
        if (self.monto_entrada < 0):
            raise ValidationError({"monto_entrada": _("El monto de entrada debe ser igual o mayor a 0")})

        # No es posible realizar cambios de divisa entre la misma divisa.
        if (self.entrada == self.salida):
            raise ValidationError({"salida": _("La moneda de salida debe ser distinta a la moneda de entrada"), "entrada": _("La moneda de entrada debe ser distinta a la moneda de salida")})

        # Establecemos el monto de salida.
        self.monto_salida = self.__GetMontoSalida()

        # Validamos la disponibilidad de la cuenta de salida.
        if (self.salida):
            if (self.salida.GetDisponible() < self.monto_salida):
                raise ValidationError({"salida": _("La cuenta en {} no tiene fondos suficientes para realizar esta transacción".format(self.salida.moneda.simbolo))})
        else:
            # Si no hay una salida, no tiene porque 
            # existir un monto de salida y una tasa.
            self.monto_salida = 0
            self.tasa_entrada = 0
            self.tasa_salida = 0

        # Calculamos la ganancia.
        if (self.entrada):
            if self.entrada.moneda.is_principal:
                if (not self.tasa_entrada_para_venta_del_dia):
                    if (self.salida):
                        self.tasa_entrada_para_venta_del_dia = self.salida.moneda.tasa_compra
                        # Calcular la ganancía generada.
                        # La ganancia estará generada en la moneda que recibimos del cliente. 
                        self.ganancia = self.monto_entrada / self.tasa_entrada_para_venta_del_dia
            else:
                if (not self.tasa_entrada_para_venta_del_dia):
                    if (self.entrada):
                        self.tasa_entrada_para_venta_del_dia = self.entrada.moneda.tasa_venta
                        # Calcular la ganancía generada.
                        # La ganancia estará generada en la moneda que recibimos del cliente. 
                        self.ganancia = self.tasa_entrada_para_venta_del_dia - self.tasa_entrada
        else:
            self.ganancia = 0
                
        if (not self.ganancia):
            self.ganancia = 0

        # Etiquetas
        tags = self.GetEtiquetas((str(self.almacen), str(self.persona), str(self.fecha), str(self.entrada), str(self.salida), self.monto_entrada, self.monto_salida, str(self.cajero)), False)
        self.tags += self.GetEtiqueta(self.nota, False)

        # El número del documento estará compuesto por el id del almacén y una secuencia automática única 
        # para cada documento en dicho almacén. Lo hacemos de último para que, debido al tiempo que tarda en
        # esta validación, no vaya otra instancia que también esté creando documento, tomar este número.
        if (self.numero == -1):
            numero = self.GetSiguienteNumero(self.almacen)
            # Evitamos lo más que se pueda, los duplicados. Estos pueden suceder si más de 
            # una instancia está creando una factura en el mismo almacén al mismo tiempo.
            for n in range(1000):
                if Documento.objects.filter(numero=numero):
                    numero += 1
                    continue 
                else:
                    break
            self.numero = numero
        self.tags += " {} ".format(self.numero)
        super().clean(*args, **kwargs)

    def GetDetail(self, subfields=False):
        d = utils.Detail(self, subfields=subfields)
        return d
    
    def GetDetailSubfields(self):
        """
        Obtiene el detalle incluyendo tambien los campos de sus relaciones.
        """
        return self.GetDetail(subfields=True)

    def GetDetailSubfieldsAll(self):
        """
        Obtiene el detalle incluyendo también los campos de sus relaciones y 
        los los campos de las relaciones de estas, etc.
        """
        return self.GetDetail(subfields="__all__")

    def GetImg(self):
        if (self.entrada) and (self.salida):
            return IMG_DOCUMENTO
        if (self.entrada):
            return IMG_DOCUMENTO_ENTRADA
        if (self.salida):
            return IMG_DOCUMENTO_SALIDA

    def GetTitulo(self):
        """
        Obtiene un texto que servirá como encabezado del documento.
        """
        if (self.entrada) and (self.salida):
            return "CAMBIO DE DIVISA"
        if (self.entrada):
            return "ENTRADA DE EFECTIVO"
        if (self.salida):
            return "SALIDA DE EFECTIVO"
        else:
            return "DOCUMENTO"

    def GetTasa(self):
        """
        Retorna la tasa real entre las dos monedas a la que se estuvo cambiando, 
        dividiendo el monto de salida entre el monto de entrada.
        Nota: Cuando una de las monedas es 'principal', la tasa será la tasa 
        de la otra moneda.
        """
        try:
            if (self.entrada.moneda.is_principal):
                return self.tasa_salida
        except (BaseException) as e:
            print(e)
        try:
            if (self.salida.moneda.is_principal):
                return self.tasa_entrada
        except (BaseException) as e:
            print(e)
        try:

documento/templates/documento/documento_factura_form.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}
{% load tags %}


{% block content %}

    <div class="form1 sombra1">
        <form id="form1" method="POST" class="post-form" onsubmit="setSubmit('form1')">{% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}

            {% for error in form.error_list %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            

            <table id="table-form" class="table-form" style="margin: auto">
                <tbody>
                    <tr>
                        <td class="r"><label for="id_almacen">{{ form.almacen.label }}:</label></td>
                        <td>{{ form.almacen }}{{ form.almacen.errors }}</td>
                        <td class="r"><label for="id_persona">{{ form.persona.label }}:</label></td>
                        <td>{{ form.persona }}{{ form.persona.errors }}</td>
                    </tr>
                    <tr>
                        <td class="r"><label for="id_tipo">{{ form.tipo.label }}</label></td>
                        <td>{{ form.tipo }}{{ form.tipo.errors }}</td>
                        <td rowspan="2" colspan="2">{{ form.nota }}{{ form.nota.errors }}</td>
                    </tr>
                    <tr>
                        <td class="r"><label for="id_fecha">{{ form.fecha.label }}:</label></td>
                        <td>{{ form.fecha }}{{ form.fecha.errors }}</td>
                    </tr>
                </tbody>
            </table>
            <br>

            <div id="nota1" style="background: rgba(255, 255, 0, 0.267); display: none; position: fixed; z-index: 999999; padding: 0px; margin: 0px; width: 100%; left: 0px; border: 1px dashed gray; text-align: center;">
                <h3 style="padding: 0px">Guardando...</h3>
            </div>

            <table style="margin: auto;" class="table-form">
                <tbody>
                    <tr>
                        <td colspan="3" style="text-align: center"><img src="{{ IMG_DOCUMENTO_ENTRADA }}" style="width: 40px" alt=""></td>
                        <td colspan="1"></td>
                        <td colspan="3" style="text-align: center"><img src="{{ IMG_DOCUMENTO_SALIDA }}" style="width: 40px" alt=""></td>
                    </tr>
                    <tr>
                        <td colspan="2" class="monedas entrada">
                            <div><label for="id_entrada">{{ form.entrada.label }}</label></div> 
                            <div title="{{ form.entrada.help_text }}">{{ form.entrada }}{{ form.entrada.errors }}</div>

                            <div><label for="id_monto_entrada">{{ form.monto_entrada.label }}</label></div> 
                            <div title="{{ form.monto_entrada.help_text }}">{{ form.monto_entrada }}{{ form.monto_entrada.errors }}</div>
                        </td>

                        <td colspan="2" style="width: 200px; text-align: center">
                            <img src="{{ IMG_FLECHA_DERECHA }}" style="width: 80px" alt="">
                            <div>Tasa</div> 
                            <div id="div-tasa-entrada" title="{{ form.tasa_entrada.help_text }}">{{ form.tasa_entrada }}{{ form.tasa_entrada.errors }}</div>
                            <div id="div-tasa-salida" title="{{ form.tasa_salida.help_text }}">{{ form.tasa_salida }}{{ form.tasa_salida.errors }}</div>
                        </td>

                        <td colspan="2" class="monedas salida">
                            <div><label for="id_salida">{{ form.salida.label }}</label></div> 
                            <div title="{{ form.salida.help_text }}">{{ form.salida }}{{ form.salida.errors }}</div>

                            <div><label for="id_monto_salida">{{ form.monto_salida.label }}</label></div> 
                            <div title="{{ form.monto_salida.help_text }}">{{ form.monto_salida }}{{ form.monto_salida.errors }}</div>
                        </td>
                    </tr>
                </tbody>

            </table>    

            {{ form.media }}

            <hr style="border-top: 1px dashed gray">
            <br>
            <div style="margin: auto; width: 400px">
                <input id="inputsubmit1" type="submit" value="Guardar e imprimir" style="width: 100%">
            </div>
        </form>
    </div>
    <br>



    <script>
        function setSubmit(formid) {
            var nota = document.getElementById("nota1");
            nota.style.display = "block";
            var inputsubmit = document.getElementById("inputsubmit1");
            inputsubmit.disabled = true;
            inputsubmit.value = "Enviando. Espere...";
            var form = document.getElementById(formid);
        }
    </script>



    









    <style>

        .form1 {
            width: 900px;
            border: 1px solid gray;
            margin: auto;
        }

        .table-form {
            width: 100%;
            background: none;
        }

        .table-form .r {
            text-align: right;
        }

        .table-form tr:hover {
            background: #eee !important;
        }

        .errorlist {
            position: absolute;
        }
        .errorlist:hover {
            opacity: 0.5;
        }

        .monedas {
            width: 300px;
        }
        .monedas input, .monedas select {
            width: 100%;
        }
        .monedas div {
            text-align: center;
            padding: 5px;
        }

        .ocultar {
            display: none !important;
        }
    </style>








    <script>

        $('document').ready(function(){
            document.getElementById("id_almacen").selectedIndex = 1;
            calcularMontoSalida();
            actualizarTasa();
            onChangeAlmacen();
        });


        // Al selecionar el almacén, se filtran solo las cuentas de dicho almacén.
        $("#id_almacen").change(onChangeAlmacen);
            
        
        function onChangeAlmacen() {
            var id = $("#id_almacen").val();
            $.ajax({url: "/cuenta/cuenta/json/list/?almacenid="+id, success: function(data) {

                if (data["error"] == true) {
                    return alert(data["message"]);
                }

                var select1 = document.getElementById("id_entrada");
                var select2 = document.getElementById("id_salida");
                select1.innerHTML = "";
                select2.innerHTML = "";

                var item;
                var op;

                // Elemento vacio.
                /*op = document.createElement("option");
                op.text = "-----------";
                select1.appendChild(op);
                op = document.createElement("option");
                op.text = "-----------";
                select2.appendChild(op);*/

                for (i = 0; i < data["results"].length; i++) {
                    item = data["results"][i];

                    op = document.createElement("option");
                    op.text = item["name"];
                    op.value = item["id"];
                    select1.appendChild(op);
                    if (item["orden"] == 1) {
                        select1.value = item["id"];
                    }

                    op = document.createElement("option");
                    op.text = item["name"];
                    op.value = item["id"];
                    select2.appendChild(op);
                    if (item["orden"] == 2) {
                        select2.value = item["id"];
                    }
                }

                actualizarTasa();
            }});

            
        }




        // Al seleccionar la cuenta de entrada, se establece la tasa
        // que la moneda de esta tiene configurada, al input 'tasa'.
        // Si la cuenta de entrada tiene la moneda predeterminada, entonces
        // la tasa será la de la cuenta de salida, ya que la moneda predeterminada
        // tendrá su tasa siempre en 1.
        $("#id_entrada").change(actualizarTasa);
        $("#id_salida").change(actualizarTasa);
        $("#id_monto_entrada").keyup(calcularMontoSalida);
        $("#id_monto_entrada").change(calcularMontoSalida);
        $("#id_monto_salida").keyup(calcularMontoEntrada);
        $("#id_tasa_entrada").keyup(calcularMontoSalida);
        $("#id_tasa_entrada").change(calcularMontoSalida);
        $("#id_tasa_salida").keyup(calcularMontoSalida);
        $("#id_tasa_salida").change(calcularMontoSalida);


        function actualizarTasa() {
            var entrada = $("#id_entrada").val();
            var salida = $("#id_salida").val();
            $.ajax({url: "/cuenta/cuenta/json/tasas/", success: function(data) {

                try {
                    $("#id_tasa_entrada").val(data["results"][entrada]["compra"]);
                } catch (error) {
                    $("#id_tasa_entrada").val("");
                }

                try {
                    $("#id_tasa_salida").val(data["results"][salida]["venta"]);
                } catch (error) {
                    $("#id_tasa_salida").val("");
                }
                
                try {
                    calcularMontoSalida();
                } catch (error) {
                    
                }
            }});
        
        ocultarTasaMonedaPredeterminada();
        
        }


        // Ocultar la casilla de tasa de la moneda predeterminada
        // ya que está siempre será 1 sin importar modificación.
        function ocultarTasaMonedaPredeterminada() {
            var entrada = $("#id_entrada").val();
            var salida = $("#id_salida").val();
            $.ajax({url: "/cuenta/cuenta/json/predeterminada/", success: function(data) {

                if (data["error"] == true) {
                    return alert(data["message"]);
                }

                if (data["results"]["id"].value == entrada) {
                    $("#id_tasa_entrada").addClass("ocultar");
                }
                else {
                    $("#id_tasa_entrada").removeClass("ocultar");
                }

                if (data["results"]["id"].value == salida) {
                    $("#id_tasa_salida").addClass("ocultar");
                }
                else {
                    $("#id_tasa_salida").removeClass("ocultar");
                }

            }});
        }



        // Calcula el monto de salida.
        function calcularMontoSalida() {
            var entrada = document.getElementById("id_entrada").value;
            var salida = document.getElementById("id_salida").value;
            var monto = document.getElementById("id_monto_entrada").value;
            var tasa1 = document.getElementById("id_tasa_entrada").value;
            var tasa2 = document.getElementById("id_tasa_salida").value;
            $.ajax({url: "/documento/documento/json/calcular/monto-salida/?entrada=" + entrada + "&salida=" + salida + "&monto=" + monto + "&tasa1=" + tasa1 + "&tasa2=" + tasa2,  success: function(data) {
                if (data["error"] == true) {
                    return;
                }
                var monto = data["results"];
                if (monto > 0) {
                    $("#id_monto_salida").val(data["results"]);
                }
                else {
                    $("#id_monto_salida").val("");
                }
            }});
        }


        // Calcula el monto de salida.
        function calcularMontoEntrada() {
            var entrada = document.getElementById("id_entrada").value;
            var salida = document.getElementById("id_salida").value;
            var monto = document.getElementById("id_monto_salida").value;
            var tasa1 = document.getElementById("id_tasa_entrada").value;
            var tasa2 = document.getElementById("id_tasa_salida").value;
            $.ajax({url: "/documento/documento/json/calcular/monto-entrada/?entrada=" + entrada + "&salida=" + salida + "&monto=" + monto + "&tasa1=" + tasa1 + "&tasa2=" + tasa2,  success: function(data) {
                if (data["error"] == true) {
                    return;
                }
                $("#id_monto_entrada").val(data["results"]);
            }});
        }



        // Guarda el documento, abre el dialogo de impresión y
        // se mantiene en esta misma página para la creación de 
        // un nuevo documento.
        function guardarImprimir() {
            $("#form1").submit();
        }



    </script>
    
    

{% endblock %}

documento/templates/documento/documento_form.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}
{% load tags %}


{% block content %}

    <div class="form1">
        <form id="form1" method="POST" class="post-form">{% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            <table>
                {{ form.as_table }}
            </table>

            {% if object.is_borrador == 'false' %}
            <input type="submit" value="Guardar">
            {% endif %}
            
            {{ form.media }}

            <br>
            <input type="submit" value="Guardar documento">
        </form>
    </div>
    <br>





    
    

    <script>
        // Al selecionar el almacén, se filtran solo las cuentas de dicho almacén.
        $("#id_almacen").change(function() {
            var id = $("#id_almacen").val();
            $.ajax({url: "/cuenta/cuenta/json/list/?almacenid="+id, success: function(data) {

                if (data["error"] == true) {
                    return alert(data["message"]);
                }

                var select1 = document.getElementById("id_entrada");
                //var select2 = document.getElementById("id_salida");
                select1.innerHTML = "";
                //.innerHTML = "";

                var item;
                var op;

                // Elemento vacio.
                op = document.createElement("option");
                op.text = "-----------";
                select1.appendChild(op);
                //op = document.createElement("option");
                //op.text = "-----------";
                //select2.appendChild(op);

                for (i = 0; i < data["results"].length; i++) {
                    item = data["results"][i];

                    op = document.createElement("option");
                    op.text = item["name"];
                    op.value = item["id"];
                    select1.appendChild(op);

                    //op = document.createElement("option");
                    //op.text = item["name"];
                    //op.value = item["id"];
                    //select2.appendChild(op);
                }
            }});
        });




        // Al seleccionar la cuenta de entrada, se establece la tasa
        // que la moneda de esta tiene configurada, al input 'tasa'.
        // Si la cuenta de entrada tiene la moneda predeterminada, entonces
        // la tasa será la de la cuenta de salida, ya que la moneda predeterminada
        // tendrá su tasa siempre en 1.
        $("#id_entrada").change(function() {
            var entrada = $("#id_entrada").val();
            var salida = $("#id_salida").val();
            $.ajax({url: "/cuenta/cuenta/json/detail/?id="+entrada, success: function(data) {

                $("#id_tasa").val(data["results"]["moneda__tasa_compra"]["value"]);
            }});
        });




        // Calculamos el monto de salida.
        $("#id_monto_entrada").change(function() {
            var entrada = document.getElementById("id_entrada").value;
            var salida = document.getElementById("id_salida").value;
            var monto = document.getElementById("id_monto_entrada").value;
            var tasa = document.getElementById("id_tasa").value;
            $.ajax({url: "/documento/documento/json/calcular/monto-salida/?entrada=" + entrada + "&salida=" + salida + "&monto=" + monto + "&tasa=" + tasa, success: function(data) {
                if (data["error"] == true) {
                    return alert(data["message"]);
                }
                $("#id_monto_salida").val(data["results"]);
            }});
        });


    </script>
    
    

{% endblock %}

documento/templates/documento/documentotipo_form.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}


{% block content %}

    <div class="form1">
        <form id="form1" method="POST" class="post-form">{% csrf_token %}

            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
            <table>
                {{ form.as_table }}
            </table>

            {% if object.is_borrador == 'false' %}
            <input type="submit" value="Guardar">
            {% endif %}
            
            {{ form.media }}

            <input type="submit" value="Guardar">
        </form>
    </div>

    <br>


    

{% endblock %}

documento/templates/documento/documentotipo_list.html
{% extends 'base/base.html' %}
{% load static %}
{% load i18n %}





{% block content-header %}
<div class="submenu">
    <ul class="links">
        {% for item in menu_documentos %}
          <li>
              <a href="{{ item.url }}">
                  <img src="{{ item.img }}" alt="">
                  <span>{{ item.name }}</span>
              </a>
          </li>
        {% endfor %}
    </ul>
</div>
{% endblock content-header %}


{% block content %}
    {# ------ CUADRO DE BUSQUEDA -------- #}
    <form id="form-search" action="">
        <div class="search-box">
            <table style="width: 100%">
                <tbody>
                    <tr>
                        <td>
                            <div class="search-box-input">
                                <input type="search" id="search1" name="q" placeholder="Buscar...">
                            </div>
                        </td>
                        <td><div><input type="submit" value="Buscar"></div></td>     
                    </tr>
                </tbody>
            </table>
        </div>

        <script>
            // Establecemos el valor al input:search
            $("#search1").val("{{ request.GET.q }}");
        </script>
    </form>
    <br>

    <div class="detail">
        <table class="table-list" style="width: 100%">
            <tbody>
                <tr>
                    <th></th>
                    <th>Referencia</th>
                    <th>Nombre</th>
                    <th>Modo</th>
                </tr>
                {% for obj in object_list  %}
                  <tr onclick="goToURL('{{ obj.get_absolute_url }}');">
                      <td><img src="{{ obj.GetImg }}" alt=""></td>
                      <td>{{ obj.codename }}</td>
                      <td>{{ obj.name }}</td>
                      <td>{{ obj.mode }}</td>
                  </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}